fix: Add cozy-sharing to transformIgnorePatters
This caused unit tests to fail since the upgrade of harvest

SyntaxError: Cannot use import statement outside a module