fix: Update cozy-authentication and cozy-bar
Needed to update cozy-bar to 10.0.0 because of cozy-ui and this message on build:
```
Can't resolve 'cozy-ui/transpiled/react/hooks/useBreakpoints' in '/home/doubleface/Workspace/cozy-banks/node_modules/cozy-bar/transpiled'
```

Needed to update cozy-authentication to 3.0.0 because of cozy-ui and this message on build:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'cozy-ui/transpiled/react/Modal' in
'/home/doubleface/Workspace/cozy-banks/node_modules/cozy-authentication/dist'
```

But cozy-authentication still needs more updates regarding cozy-ui and
is associated to cozy-ui@40.9.1 at the moment

I have no idea of the impact of these update of cozy-bar and
cozy-authentication