feat: Upgrade cozy-scripts
The main goal of this update was to update https://github.com/cozy/cozy-libs/tree/master/packages/babel-preset-cozy-app to benefit from the node 16 target in order to have a more readable output for service watches.

However, the latest version of cozy-scripts does not include version 2 of babel-preset-cozy-app. I did try to update it by directly adding the library as a dependency, but I got a lot of subsequent babel errors: "Parsing error: [BABEL] /cozy-banks/src/utils/mergeSets.js: Cannot find module '@babel/helper-string-parser'". This update will have to wait for the next one.

No BC to apply here since we manualy use the cozy-scripts webpack config